name: Actions Workflow

on: [push]

jobs:
  run-new-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls
      - name: checkout
        uses: actions/checkout@v1
      - name: List Files
        run: |
          pwd
          ls -a
      - name: Simple JavaScript Action
        id: hello
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Nhialee Yang
      - name: Log Greeting Time
        run: echo "${{ steps.hello.outputs.time }}"
