name: Shell commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: eccho a string
        run: echo "Hello World!"
      - name: multiline script
        run: |
          node -v
          npm -v

name: other shell commands v2

on: [push]

jobs:
  run-new-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a new string
        run: echo "hello new new world for Nhialee Yang"
      - name: another multiline script
        run: |
          node -v
          npm -v